server:
  port: 8080
  servlet:
    context-path: /maintain/monitors
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./.h2/mqdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;MODE=Oracle;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:script/CREATE_TABLE.sql
  h2:
    console:
      enabled: true
      path: /h2

mqws:
  path: /maintain/monitors/queuews
  port: 8083
